version: 2.1 # Use version 2.1 to enable orb usage.

orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.

jobs:
  build: 
    docker:
      - image: "circleci/node:12"
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache{{ checksum "yarn.lock" }}
      - run: 
          name : install-yarn
          command : 'yarn global add node-gyp && yarn install'
      - save_cache:
          key: yarn-cache{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

  test:
    docker:
      - image: "circleci/node:12"
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache{{ checksum "yarn.lock" }}
      - run: 
        name: test-ci
        command: 'yarn test:ci'
      - save_cache:
          key: yarn-cache{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
  lint:
    docker:
      - image: "circleci/node:12"
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache{{ checksum "yarn.lock" }}
      - run: 
        name: lint-ci
        command: 'yarn lint && yarn format:check'
      - save_cache:
          key: yarn-cache{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
        